[package]
name = "surrealdb"
version = "0.1.0"
authors = ["Maxwell Flitton <maxwellflitton@gmail.com>"]
edition = "2018"

[dependencies]
surrealdb = { version = "1.2.0",  features = ["protocol-ws", "protocol-http", "kv-mem"] }
serde = "^1.0.164"
futures = { version="0.3.30", features = ["executor"] }
once_cell = "1.19.0"
serde_json = "^1.0.97"
crossbeam-channel = "^0.5"
thiserror = "^1.0.43"
pyo3 = "0.20.0"
pyo3-asyncio = { version = "0.20",  features = ["unstable-streams", "attributes", "tokio-runtime"] }
uuid = { version = "1.3.4", features = [ "v4", "fast-rng", "macro-diagnostics" ] }

[dev-dependencies]
tokio = { version = "1.36.0", features = ["full"] }
bollard = "*"
futures-util-preview = "0.2.2"
pyo3 = { version = "0.20.3", features = ["auto-initialize"] }

[lib]
name = "rust_surrealdb"
crate-type=["cdylib"]

[features]
# must be enabled when building with `cargo build`, maturin enables this automatically
extension-module = ["pyo3/extension-module"]

[build-dependencies]
version_check = "0.9.4"
# used where logic has to be version/distribution specific, e.g. pypy
pyo3-build-config = { version = "0.20.2" }
